# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 나영원의 포트폴리오
description: 'portfolio'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://foeverna.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

logo: 
  logo: 'img/logo/myLogo.jpg'
  light: 'img/logo/myLogo.jpg'
  mobile: ''
favicon:  'img/favicon/favicon.ico'

vendor: 
  name: DUCOR
  url: "https://themeforest.net/user/ducor"

html_directionality:  'rtl' # ltl ( default ) "rtl", ltl
# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

permalink: /blog/:title:output_ext
paginate: 6
paginate_path: "/blog/page:num/"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

comments:
  provider               : 'disqus' # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : 'patrick-ducor' # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# google map key
google_map_key           : 'AIzaSyDz2w7HUaWudHwd7AWQpCL48Qs050WOn9s' # false (default),

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

##
getform_id: # to go https://getform.io/ and create an account for contact form 


##########################################################################
################# seo ####################################################
##########################################################################
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :
og_image                 : '/images/profile.jpg' # Open Graph/Twitter default site image
header: 
  - image                 : '/images/profile.jpg'

###########################################################################
###########################   Home / hero  ################################
###########################################################################

first_name: 배우는개발자
last_name: 나영원
date_of_bath: '1989-03-02 00:00'
email: 'fovena@gmail.com'
phone: '010 6229 5429'
address: '경기도 안양시 동안구'
github: 'github.com/FoeverNa'
study: '건국대학교 경영학 학사'
blog: 'velog.io/@foeverna'
cv_download_link: 'https://drive.google.com/file/d/17eeIEEkXBV_QFkny0hFVxMrYnenoCaEn/view?usp=sharing'
user_intro: ' 남들 보다 늦은 시기에 개발 분야에 입문했지만 그만 큼 더 열정과 열심을 가지고 성장하는 개발자가되기 위해 노력하고 빠르게 성장하고 있습니다. 다양한 분야에서 다양한 사람들을 만나는 경험을 통해 스프트웨어 기술을 통해 세상을 더 편리하게 만드는 것과 협업에 관심을 가지고 있습니다. 추후수정바랍니다'


freelance_hire: true
professions: 
  - photographer
  - blogger
  - web developer
  - freelancer
  - photographer
author_description: "<strong>Hello, I’m a Patrick</strong>, web-developer based on Paris. <br> I have rich experience in web site design &amp; building <br> and customization. Also I am good at <strong>html, css, <br> wordpress, php, jquery, bootstrap.</strong>"
social_link:
  - name: facebook
    icon: "xcon-facebook"
    link: "#"
  - name: twitter 
    icon: "xcon-twitter"
    link: "#"

  - name: linkedin 
    icon: "xcon-linkedin"
    link: "#"
  - name: instagram 
    icon: "xcon-instagram"
    link: "#"
  - name: behance 
    icon: "xcon-behance"
    link: "#"


#############################################
######### Our Services ######################
#############################################
our_services_title: 'Skills'
our_services_tagline: 'What I Can Do'

our_services:
  - name: "Web Development"
    image: "img/svg/source.svg"
    description: "Web design is a similar process of creation, with the intention of presenting.."

  - name: 'Brand Identity'
    image: 'img/svg/line-chart.svg'
    description: 'Web design is a similar process of creation, with the intention of presenting...'
  
  - name: 'Creative Design'
    image: 'img/svg/light-bulb.svg'
    description: 'Web design is a similar process of creation, with the intention of presenting...'
  
  - name: 'Adobe Illustrator'
    image: 'img/svg/adobe-illustrator.svg'
    description: 'Web design is a similar process of creation, with the intention of presenting...'
  
  - name: 'Adobe Photoshop'
    image: 'img/svg/adobe-photoshop.svg'
    description: 'Web design is a similar process of creation, with the intention of presenting...'
  
  - name: 'Social Media'
    image: 'img/svg/twitter-1.svg'
    description: 'Web design is a similar process of creation, with the intention of presenting...'

##################################################################
################  professional_skills ############################
##################################################################
professional_skill_title: '저는 <span>짧은 시간</span>, 성자하여 웹 백엔드 부분 기술들을 익혀 나갈 수 있었습니다..'
professional_skill_description: '단순한 기능 구현보다는 안정성과 유연성에 관심이 있으며 테스트 주도 개발에 관심이 있습니다. '

professional_skills:
  - name: 'Java'
    percentage: '80'
  
  - name: 'Spring / SpringBoot'
    percentage: '70'
  
  - name: 'RMDB'
    percentage: '60'
  
  - name: 'AWS'
    percentage: '60'

##########################################
################ portfolios ##############
#########################################
portfolio_title: 'Creative Works'
portfolio_tagline: 'Portfolios'
portfolio_categories: ['개인프로젝트', '팀프로젝트']

portfolios: 
  - main_image: 'img/portfolio/sweetypie.png'
    title: '클릭시 상세페이지로 이동합니다'
    type: 'video'
    category: '팀프로젝트'
    video_link: 'https://www.miricanvas.com/v/1am4h9'

  
#############################################
############ EXPERIENCE #####################
#############################################
experience_title: 'Experience'
experience_tagline: 'Working Process'
experience_description: ''

educations:
  - year: '2009 - 2013'
    title: 'University of Chicago'
    description: 'Independent study is a form of education offered by many high schools, colleges, and other educational institutions. It is sometimes referred to as directed study.'
  - year: '2006 - 2009'
    title: 'Christofer College'
    description: 'Independent study is a form of education offered by many high schools, colleges, and other educational institutions. It is sometimes referred to as directed study.'
  - year: '1996 - 2006'
    title: 'Secondary School'
    description: 'Independent study is a form of education offered by many high schools, colleges, and other educational institutions. It is sometimes referred to as directed study.'

experiences:
  - year: '2018 - Current'
    title: 'Web Developer'
    description: 'Web development refers to building, creating, and an maintaining websites. It includes aspects such as web design, web programming, and database management.'
  - year: '2015 - 2018'
    title: 'App Developer'
    description: 'Web development refers to building, creating, and an maintaining websites. It includes aspects such as web design, web programming, and database management.'
  - year: '2013 - 2015'
    title: 'Ui/Ux Designer'
    description: 'Web development refers to building, creating, and an maintaining websites. It includes aspects such as web design, web programming, and database management.'

  
